version: '3.7'
services:
    php:
        build: .
        ports:
            - '5002:80'
        volumes:
            - './src:/var/www/html'
        depends_on:
          - postgres
    postgres:
      image: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=toto
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - pgdata_phpd:/var/lib/postgresql/data
        - pgconf_phpd:/etc/postgresql
        - pglog_phpd:/var/log/postgresql
volumes:
  pgdata_phpd:
    driver: local
  pgconf_phpd:
    driver: local
  pglog_phpd:
    driver: local